### PR TITLE
refactor(corelib): using rust macro instead of erb

### LINKED ISSUE #124: Replace code generation with build script
Currently some .rs files are generated from .erb with Ruby. It is nice if we can drop ruby from dependencies.

https://doc.rust-lang.org/cargo/reference/build-script-examples.html

### PR DESCRIPTION
**Pull request by aisk**
I think it's cool to using rust macro instead of using erb template to generator methods, because this is the builtin stuff in the language and thus does not need a "build" process to build shiika, so I just took a try, and it works. This is just a experiment so just int is implemented.

The generated codes should be like before, expected the return type is determined in runtime (not in macro expanding process), but I think rustc is smart enough to optmize it and does not actually introduce runtime cost maybe?

@yhara if you think this is ok, I'll try using the same mechanism to implement float methods.

close #124.

### CODE REVIEW

**Comment by aisk** [comment]
Seems this project have no CI, but `$ cargo test` is passed on my machine.

**Comment by aisk** [comment]
A little explaination on this change: `$body` should be an `expr` type and should be passed a closure to the macro, but currently rust does not allow specify lifetime on closurem, so I just make it as a funtion definition. In future if rust allow specify lifetime on closure, I think the codes can be reduced.

**Comment by yhara** [comment]
> if you think this is ok, I'll try using the same mechanism to implement float methods.

@aisk Yes I once tried to write it with macro but I couldn't get it work. Please go ahead.

**Comment by aisk** [comment]
@yhara Hi I think this PR is finished now. And I did a little refactor that split the macro into two for arithmetic operator and comparison operator and thus there should be no any runtime cost and the generated codes should be exactly like before.

**Comment by yhara** [comment]
Merged! Confirmed CI passes. https://github.com/yhara/shiika/runs/1060504265

**Pull request merged**
